### ISSUE TITLE
Docker build on arm64 fails

### ISSUE THREAD

**Issue by Glagnar** [Borda/docker_python-opencv-ffmpeg#3]
Small error when building on arm64:

```bash
 ---> 9f0e2cb95ad0
Step 5/5 : RUN update-alternatives --install /usr/bin/python${PYTHON_VERSION%%.*} python${PYTHON_VERSION%%.*} /usr/bin/python${PYTHON_VERSION} 1 &&     update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 1 &&     python --version &&     python -c "import cv2 ; print(cv2.__version__)"
 ---> Running in 75831159731a
update-alternatives: using /usr/bin/python3.8 to provide /usr/bin/python3 (python3) in auto mode
update-alternatives: using /usr/bin/python3.8 to provide /usr/bin/python (python) in auto mode
Python 3.8.0
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:
```

**Comment by Glagnar** [comment]
Adding libatlas-base-dev to list of installs, makes it work.

**Comment by Borda** [comment]
@Glagnar mind trying it now after some more fixes, I found that some OpenCV needed different requirements...
Moreover, you can use already build docker images from [Docker Hub](https://hub.docker.com/r/borda/docker_python-opencv-ffmpeg/tags), see the tags there 🐰
