### ISSUE TITLE
import cv2  got error

### ISSUE THREAD

**Issue by Hu1-Li** [Borda/docker_python-opencv-ffmpeg#40]
uname -a 
```
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

docker -v 

```
Docker version 24.0.6, build ed223bc

```

run with 
```
docker run --rm -it  borda/docker_python-opencv-ffmpeg:cpu-py3.8-cv4.8.1 python -c "import cv2"
```

got 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

I found the so file under `/lib/x86_64-linux-gnu/`

but it works on windows wsl with ubuntu.

any suggestions?

**Comment by Borda** [comment]
seems all works fine for me...
```
$ docker run --rm -it  borda/docker_python-opencv-ffmpeg:cpu-py3.8-cv4.8.1 python -c "import cv2"
Unable to find image 'borda/docker_python-opencv-ffmpeg:cpu-py3.8-cv4.8.1' locally
cpu-py3.8-cv4.8.1: Pulling from borda/docker_python-opencv-ffmpeg
edaedc954fb5: Pull complete 
bb21fd843d62: Pull complete 
597f3ed551e0: Pull complete 
338ad4953d39: Pull complete 
Digest: sha256:2e717fa85eef5072de248e296ceacfd751dea741aa059328ab8d2ae79d8ac50c
Status: Downloaded newer image for borda/docker_python-opencv-ffmpeg:cpu-py3.8-cv4.8.1
$ docker -v
Docker version 24.0.7, build afdd53b
